spring:
  application:
    name: ms-cliente-producto
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://localhost:5433/ms_cliente_producto
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
